### todo_ui.R --- 
## Filename: todo_ui.R
## Description: 
## Author: Noah Peart
## Created: Sat Oct 31 01:41:27 2015 (-0400)
## Last-Updated: Sat Oct 31 02:07:25 2015 (-0400)
##           By: Noah Peart
######################################################################
bootstrapPage(
    HTML('<p>All of the TODO stuff is generated by orgmode.</p>'),
    a(href="/org/html/index.html", target="_blank", "Here")
)
